server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  add_header Content-Security-Policy "default-src 'self'; connect-src 'self' http://localhost:3000; style-src 'self' 'unsafe-inline'";
  location / {
    try_files $uri /index.html;
  }
}
