services:
  backend:
    ports: ["3001:3000"]
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: sh -c "npx prisma migrate deploy --schema ./schema.prisma && node dist/server.js"
